#!/bin/bash

set -x # Print commands and their arguments as they are executed.

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER apache
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf


